# Neighborhood Computations

In [119]:
import numpy as np
import igl
import meshplot
meshplot.offline()

In [120]:
bunny_v, bunny_f = igl.read_triangle_mesh("data/bunny.off")
cube_v, cube_f = igl.read_triangle_mesh("data/cube.obj")
sphere_v, sphere_f = igl.read_triangle_mesh("data/sphere.obj")

v = cube_v.copy()
f = cube_f.copy()

In [121]:
meshplot.plot(bunny_v, bunny_f, shading={"wireframe": True}, filename = "default_bunny")

Plot saved to file default_bunny.html.


In [122]:
p = meshplot.plot(cube_v, cube_f, shading={"wireframe": True}, filename = "default_cube")

Plot saved to file default_cube.html.


In [123]:
meshplot.plot(sphere_v, sphere_f, shading={"wireframe": True}, filename = "default_sphere")

Plot saved to file default_sphere.html.


In [124]:
## Vertex-to-Face Relations

## Vertex-to-Vertex Relations

In [125]:

vertex_face_relation = igl.vertex_triangle_adjacency(f,len(f))
vertex_vertex_relation = igl.adjacency_list(f)
print("Vertex to face relation\n",vertex_face_relation,"\nfirst array contains all the faces a vertice touches, the second array will tell the indexes where a new triangle starts and the index of said position will be the face number")
print("Vertex to Vertex relation\n",vertex_vertex_relation,"a 2d array, where each array corrisponds to a vertex, and the components of each vertex are adjacent vertices")
print("Face construction\n",f)
print("Vertex positions\n",v)

Vertex to face relation
 (array([ 0,  6,  7, 10, 11,  0,  1,  7,  8,  0,  1,  2, 11,  1,  2,  3,  8,
        9,  2,  3,  4, 10, 11,  3,  4,  5,  9,  4,  5,  6, 10,  5,  6,  7,
        8,  9], dtype=int32), array([ 0,  5,  9, 13, 18, 23, 27, 31, 36, 36, 36, 36, 36], dtype=int32)) 
first array contains all the faces a vertice touches, the second array will tell the indexes where a new triangle starts and the index of said position will be the face number
Vertex to Vertex relation
 [[1, 2, 4, 6, 7], [0, 2, 3, 7], [0, 1, 3, 4], [1, 2, 4, 5, 7], [0, 2, 3, 5, 6], [3, 4, 6, 7], [0, 4, 5, 7], [0, 1, 3, 5, 6]] a 2d array, where each array corrisponds to a vertex, and the components of each vertex are adjacent vertices
Face construction
 [[0 1 2]
 [2 1 3]
 [2 3 4]
 [4 3 5]
 [4 5 6]
 [6 5 7]
 [6 7 0]
 [0 7 1]
 [1 7 3]
 [3 7 5]
 [6 0 4]
 [4 0 2]]
Vertex positions
 [[-0.5 -0.5  0.5]
 [ 0.5 -0.5  0.5]
 [-0.5  0.5  0.5]
 [ 0.5  0.5  0.5]
 [-0.5  0.5 -0.5]
 [ 0.5  0.5 -0.5]
 [-0.5 -0.5 -0.5]
 [ 0.5 -0

## Shading

Meshplot requires per vertex normals, so we need to "explode" the mesh

In [126]:
# give each face 3 unique vertexes
new_f = f.copy()
map_list = []
for i in range (0,len(f)):
    for j in range (0,len(f[i])):
        #print (i*len(f[i])+j)
        map_list.append(new_f[i][j])
        new_f[i][j] = i*len(f[i])+j
print(new_f)
#print(map_list)

# copy old vertices to create new vertices
new_v = np.array([[0.0, 0.0, 0.0]]*len(map_list))
for i in range(0,len(map_list)):
    new_v[i] = v[map_list[i]]
print(new_v)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]
 [24 25 26]
 [27 28 29]
 [30 31 32]
 [33 34 35]]
[[-0.5 -0.5  0.5]
 [ 0.5 -0.5  0.5]
 [-0.5  0.5  0.5]
 [-0.5  0.5  0.5]
 [ 0.5 -0.5  0.5]
 [ 0.5  0.5  0.5]
 [-0.5  0.5  0.5]
 [ 0.5  0.5  0.5]
 [-0.5  0.5 -0.5]
 [-0.5  0.5 -0.5]
 [ 0.5  0.5  0.5]
 [ 0.5  0.5 -0.5]
 [-0.5  0.5 -0.5]
 [ 0.5  0.5 -0.5]
 [-0.5 -0.5 -0.5]
 [-0.5 -0.5 -0.5]
 [ 0.5  0.5 -0.5]
 [ 0.5 -0.5 -0.5]
 [-0.5 -0.5 -0.5]
 [ 0.5 -0.5 -0.5]
 [-0.5 -0.5  0.5]
 [-0.5 -0.5  0.5]
 [ 0.5 -0.5 -0.5]
 [ 0.5 -0.5  0.5]
 [ 0.5 -0.5  0.5]
 [ 0.5 -0.5 -0.5]
 [ 0.5  0.5  0.5]
 [ 0.5  0.5  0.5]
 [ 0.5 -0.5 -0.5]
 [ 0.5  0.5 -0.5]
 [-0.5 -0.5 -0.5]
 [-0.5 -0.5  0.5]
 [-0.5  0.5 -0.5]
 [-0.5  0.5 -0.5]
 [-0.5 -0.5  0.5]
 [-0.5  0.5  0.5]]


### Flat Shading

In [127]:
list2 = [[0.0],[0.0],[0.0]]
n = igl.per_face_normals(new_v,new_f,np.array(list2))
print(n)
p = meshplot.plot(new_v, new_f, n=n, shading={"flat": True}, filename = "flat_shading")
#p.add_lines(new_v, new_v + 0.01*n)

[[ 0.  0.  1.]
 [-0.  0.  1.]
 [-0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  0. -1.]
 [ 0.  0. -1.]
 [ 0. -1.  0.]
 [ 0. -1.  0.]
 [ 1. -0.  0.]
 [ 1.  0.  0.]
 [-1.  0.  0.]
 [-1.  0.  0.]]
Plot saved to file flat_shading.html.


### Per-vertex Shading

In [128]:
n = igl.per_vertex_normals(new_v, new_f)
#print(n)
#print(map_list)
new_n = np.array([[0.0, 0.0, 0.0]]*len(v))
list_n = [[0.0,0.0,0.0]] * len(v)
for j in range (0,len(v)):
    x = 0;
    y = 0;
    z = 0;
    c = 0;
    for i in range(0,len(map_list)):
        #print(map_list[i])
        if(map_list[i] == j):
            #print("match")
            x += new_v[j][0]
            y += new_v[j][1]
            z += new_v[j][2]
            c += 1
    if c != 0:
        x = x/c
        y = y/c
        z = z/c
    #print(x,y,z)
    new_n[j] = x,y,z
p = meshplot.plot(new_v, new_f, n=new_n, shading={"flat": False}, filename = "per_vertex_shading")
#p.add_lines(v, v + 0.01*new_n)

Plot saved to file per_vertex_shading.html.


### Per-corner Shading

In [129]:
n = igl.per_corner_normals(new_v, new_f,0.2)
print(n)
new_n = np.array([[0.0, 0.0, 0.0]]*len(v))
list_n = [[0.0,0.0,0.0]] * len(v)
for j in range (0,len(v)):
    x = 0;
    y = 0;
    z = 0;
    c = 0;
    for i in range(0,len(map_list)):
        #print(map_list[i])
        if(map_list[i] == j):
            #print("match")
            x += new_v[j][0]
            y += new_v[j][1]
            z += new_v[j][2]
            c += 1
    if c != 0:
        x = x/c
        y = y/c
        z = z/c
    #print(x,y,z)
    new_n[j] = x,y,z
print(new_n)
p = meshplot.plot(new_v, new_f, n=new_n, shading={"flat": False}, filename = "per_corner_shading")

[[ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  0. -1.]
 [ 0.  0. -1.]
 [ 0.  0. -1.]
 [ 0.  0. -1.]
 [ 0.  0. -1.]
 [ 0.  0. -1.]
 [ 0. -1.  0.]
 [ 0. -1.  0.]
 [ 0. -1.  0.]
 [ 0. -1.  0.]
 [ 0. -1.  0.]
 [ 0. -1.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [-1.  0.  0.]
 [-1.  0.  0.]
 [-1.  0.  0.]
 [-1.  0.  0.]
 [-1.  0.  0.]
 [-1.  0.  0.]]
[[-0.5 -0.5  0.5]
 [ 0.5 -0.5  0.5]
 [-0.5  0.5  0.5]
 [-0.5  0.5  0.5]
 [ 0.5 -0.5  0.5]
 [ 0.5  0.5  0.5]
 [-0.5  0.5  0.5]
 [ 0.5  0.5  0.5]]
Plot saved to file per_corner_shading.html.


## Connected Components

In [130]:
c = igl.face_components(f)
print(c, "size of shape:", len(c), "number of components:", max(c) + 1)
for i in range (0, max(c + 1)):
    count = 0
    for j in range (0, len(c)):
        if(i == c[j]):
            count += 1
    print("Component number:", i, "Size of component:", count)
p = meshplot.plot(v, f, c=c, filename = "connect_components")

[0 0 0 0 0 0 0 0 0 0 0 0] size of shape: 12 number of components: 1
Component number: 0 Size of component: 12
Plot saved to file connect_components.html.


## A simple subdivision scheme

In [131]:
# NOTE: this algorithm is very inefficient, but it works for the sphere and cube. The bunny does work, it just takes forever

# initialize the double prime
f_double_prime = np.zeros((len(f)*3,3))
# silly method to initialize the array since numpy is dumb, use better method in future
v_double_prime = np.zeros((len(v)+len(f),3))
for i in range(0,len(v)):
    v_double_prime[i] = v[i]
# Loop through all the faces and create a new midpoint vertex
for i in range(0,len(f)):
    m_f = np.array([0,0,0])
    # location of new vertex to add
    m_f = v[f[i][0]]/3 + v[f[i][1]]/3 + v[f[i][2]]/3
    # add new vertex to list
    v_double_prime[i+len(v)] = m_f
    # create new triangles to the list
    t_1 = np.array((f[i][0],f[i][1],i+len(v)))
    t_2 = np.array((f[i][0],i+len(v),f[i][2]))
    t_3 = np.array((i+len(v),f[i][1],f[i][2]))
    f_double_prime[(i*3)] = t_1
    f_double_prime[(i*3)+1] = t_2
    f_double_prime[(i*3)+2] = t_3
p = meshplot.plot(v_double_prime, f_double_prime, shading={"wireframe": True},filename="simple_sub_phase1")
adj = igl.adjacency_list(f)
v_prime = np.zeros((len(v)+len(f),3))
# loop through all of the old vertices
for i in range (0,len(adj)):
    x = 0
    y = 0
    z = 0
    degree = len(adj[i])
    a_n = (4-(2*np.cos((2*np.pi)/degree)))/9
    #sum up the positions of adjacent vertices
    for j in range (0, degree):
        x += v[adj[i][j]][0]
        y += v[adj[i][j]][1]
        z += v[adj[i][j]][2]
    neighbor_pos = np.array((x,y,z)) * (a_n/degree)
    original_pos = (1-a_n) * v[i]
    new_pos = original_pos + neighbor_pos
    v_prime[i] = new_pos
    
# append vertices from v_double_prime to v_prime
for i in range(len(adj),len(v_prime)):
    v_prime[i] = v_double_prime[i]

p = meshplot.plot(v_prime, f_double_prime, shading={"wireframe": True},filename="simple_sub_phase2")
# convert the numpy array to int64 to work with edge_topology
f_double_prime = f_double_prime.astype('int64')
f_prime = f_double_prime.copy()
ev, fe, ef = igl.edge_topology(v_prime, f_double_prime)
# get every old edge
for i in range(0,len(ev)):
    if ev[i][0] < len(v) and ev[i][1] < len(v):
        triangle_id1 = -1
        triangle_id2 = -1
        # find the two triangles that share this edge number, from this we can get the vertices
        for j in range(0,len(fe)):
            if(fe[j][0] == i or fe[j][1] == i or fe[j][2] == i):
                if(triangle_id1 == -1):
                    triangle_id1 = j
                else:
                    triangle_id2 = j
        # isolate the unique alpha and beta vertices that are not part of the edge
        alpha = -1
        beta = -1
        if f_double_prime[triangle_id1][0] != ev[i][0] and f_double_prime[triangle_id1][0] != ev[i][1]:
            alpha = f_double_prime[triangle_id1][0]
        elif f_double_prime[triangle_id1][1] != ev[i][0] and f_double_prime[triangle_id1][1] != ev[i][1]:
            alpha = f_double_prime[triangle_id1][1]
        else:
            alpha = f_double_prime[triangle_id1][2]
            
        if f_double_prime[triangle_id2][0] != ev[i][0] and f_double_prime[triangle_id2][0] != ev[i][1]:
            beta = f_double_prime[triangle_id2][0]
        elif f_double_prime[triangle_id2][1] != ev[i][0] and f_double_prime[triangle_id2][1] != ev[i][1]:
            beta= f_double_prime[triangle_id2][1]
        else:
            beta = f_double_prime[triangle_id2][2]
            
        # create the swapped edge triangles and replace the originals in f_prime, make sure to leave f_double_prime unchanged.
        f_prime[triangle_id1] = np.array((ev[i][0],alpha,beta))
        f_prime[triangle_id2] = np.array((ev[i][1],alpha,beta))

p = meshplot.plot(v_prime, f_prime, shading={"wireframe": True},filename="simple_sub_final")

Plot saved to file simple_sub_phase1.html.
Plot saved to file simple_sub_phase2.html.
Plot saved to file simple_sub_final.html.
